import {$,$$,E,get,post,icon,button,badge,stats,pageHead,empty,listen,toast,modal,ask,showJSON,
        runJob,download,pickPath,bytes,when,fileIcon,highlight,jobsHTML,bindJobs,mount} from './common.js';
const info=await get('info');
let state,mode='hybrid',query='',extension='',tag='',rootFilter='',selectedId=null,currentTab='search';
const guide=`<p>Select Load demo folder to try local search without indexing your own files.</p><ol class="list-note"><li>Add a folder in Indexed folders.</li><li>Run an index scan.</li><li>Search with words from the file name or document text.</li><li>Use file types and tags to narrow the results.</li></ol><p class="muted small">Search scores are ranking values, not confidence percentages. Documents with incomplete text extraction show a coverage note. The index stores private extracted text on this PC.</p>`;
async function refresh(){state=await get('state');}
function searchArgs(){return {q:query,mode,extension,tag,root:rootFilter};}
function readFilters(){mode=$('#search-mode')?.value||mode;query=$('#search-query')?.value||'';extension=$('#type-filter')?.value||'';tag=$('#tag-filter')?.value||'';rootFilter=$('#root-filter')?.value||'';}
async function demo(){const root=await post('roots/add',{path:info.example_path});await runJob('scan',{id:root.id});query='inventory';extension='';tag='';selectedId=null;await refresh();if(currentTab==='search')await renderSearch();else location.hash='search';toast('Demo files indexed. Try inventory, warranty, or transformer.');}
function metrics(){return stats([['Indexed files',state.stats.files,'Only folders you selected','file'],['Searchable text',state.stats.searchable,'Files with extracted text','search'],['Indexed input size',bytes(state.stats.bytes),'Original files remain unchanged','folder'],['Coverage notes',state.stats.warnings,'Files that need a closer check','alert']]);}
async function renderSearch(){
  const result=await get('search',searchArgs());
  if(!result.results.some(r=>r.id===selectedId))selectedId=result.results[0]?.id||null;
  $('#view').innerHTML=pageHead('PRIVATE FILE SEARCH','Find the file. Keep it local.','Search file names and document text across the folders you choose.',button('load-demo','Load demo folder','folder','primary'))+metrics()
  +`<div class="search-bar">${icon('search')}<input id="search-query" value="${E(query)}" placeholder="Search for a receipt, project, phrase, or note..." aria-label="Search local files">${button('run-search','Search','search','primary')}</div><div class="filter-row"><select id="search-mode" aria-label="Search mode">${[['hybrid','Words and meaning'],['keyword','Words only'],['semantic','Meaning only']].map(([id,label])=>`<option value="${id}" ${mode===id?'selected':''}>${label}</option>`).join('')}</select><select id="type-filter" aria-label="File type"><option value="">All file types</option>${state.extensions.map(x=>`<option value="${E(x.extension)}" ${x.extension===extension?'selected':''}>${E(x.extension||'No extension')} (${x.count})</option>`).join('')}</select><select id="root-filter" aria-label="Indexed folder"><option value="">All indexed folders</option>${state.roots.map(r=>`<option value="${r.id}" ${String(r.id)===String(rootFilter)?'selected':''}>${E(r.name)}</option>`).join('')}</select><input id="tag-filter" value="${E(tag)}" placeholder="Filter by tag" aria-label="Tag filter" style="max-width:130px">${button('save-search','Save search','bookmark','ghost')}${button('export-search','Export results','download','ghost')}<span class="hint">${E(result.engine)} · ${result.results.length} result${result.results.length===1?'':'s'}</span></div>`
  +(result.suggestions.length?`<div class="notice info">No exact word match. Try ${result.suggestions.map(s=>`<button class="text-btn" data-suggestion="${E(s)}">${E(s)}</button>`).join(' ')}</div>`:'')
  +`<div class="split"><section class="panel"><div class="panel-head"><h2>${query?'Search results':'Indexed files'}</h2><div class="inline-meta"><span class="count-label">Try</span>${['inventory','warranty','transformer'].map(s=>`<button class="query-chip" data-suggestion="${s}">${s}</button>`).join('')}</div></div><div id="results-list">${result.results.length?result.results.map(r=>`<article class="search-hit ${r.id===selectedId?'selected':''}" data-file="${r.id}" tabindex="0" role="button" aria-label="Preview ${E(r.name)}"><div class="search-hit-head">${fileIcon(r.name)}<div style="min-width:0;flex:1"><h3>${highlight(r.name,query)}</h3><span class="small muted overflow-path" title="${E(r.path)}">${E(r.path)}</span></div>${badge(r.extension||'file','accent')}</div><p class="snippet">${highlight(r.snippet||'No extracted text is available. This result uses the file name or path.',query)}</p><div class="inline-meta">${badge(r.match_reason)}<span class="tiny muted">${bytes(r.size)}</span>${r.tags.map(t=>badge(t,'accent')).join('')}${r.warning?badge('Coverage note','warn'):''}</div></article>`).join(''):empty('No matching files',state.stats.files?'Use fewer words or clear a filter.':'Index the demo folder or add a folder from your PC.','search')}</div></section><aside class="panel" id="preview-panel"></aside></div>`;
  listen('#load-demo','click',demo);
  listen('#run-search','click',async()=>{readFilters();selectedId=null;await renderSearch();});
  listen('#search-query','keydown',async e=>{if(e.key==='Enter'){readFilters();selectedId=null;await renderSearch();}});
  listen('#type-filter,#root-filter,#search-mode','change',async()=>{readFilters();selectedId=null;await renderSearch();});
  listen('#tag-filter','keydown',async e=>{if(e.key==='Enter'){readFilters();await renderSearch();}});
  listen('[data-suggestion]','click',async(_,node)=>{query=node.dataset.suggestion;selectedId=null;await renderSearch();});
  listen('[data-file]','click',async(_,node)=>{selectedId=Number(node.dataset.file);$$('.search-hit').forEach(n=>n.classList.toggle('selected',n===node));await renderPreview();});
  listen('[data-file]','keydown',async(e,node)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectedId=Number(node.dataset.file);await renderPreview();}});
  listen('#save-search','click',async()=>{readFilters();const name=await ask('Save search','Search name',query||'Recent files');if(name!==null){await post('saved/add',{name,query,extension,tag});await refresh();toast('Search saved.');}});
  listen('#export-search','click',async()=>{readFilters();await download(await post('export',{query,mode,extension,tag,root:rootFilter,format:'csv'}));});
  await renderPreview();
}
async function renderPreview(){
  const panel=$('#preview-panel');if(!panel)return;
  if(!selectedId){panel.innerHTML=empty('File preview','Select a search result to read its indexed text.','file');return;}
  const file=await get('preview',{id:selectedId});
  panel.innerHTML=`<div class="panel-head"><h2>File preview</h2>${icon('file')}</div><div class="panel-body"><div class="row-between"><h3 style="margin:0;overflow-wrap:anywhere">${E(file.name)}</h3>${badge(file.extension,'accent')}</div><div class="key-values"><span>File size</span><strong>${bytes(file.size)}</strong><span>Text reader</span><strong>${E(file.method)}</strong><span>Last indexed</span><strong>${E(when(file.indexed))}</strong><span>File present</span><strong>${file.exists?'Yes':'No, scan the folder again'}</strong></div>${file.warning?`<div class="notice">${icon('alert')}<span>${E(file.warning)}</span></div>`:''}<div class="preview-text">${highlight(file.text||'No text layer was extracted from this file.',query)}</div><div class="divider"></div><label class="field">Tags<input id="file-tags" value="${E(file.tags.join(', '))}" placeholder="work, receipts, research"><small>Separate tags with commas. Tags stay in this app.</small></label><div class="section-actions">${button('save-tags','Save tags','check','primary')}${button('similar-files','Similar text','search','ghost')}</div><button id="copy-path" class="text-btn" style="margin-top:12px">${icon('copy')} Copy local file path</button></div>`;
  listen('#save-tags','click',async()=>{await post('tags',{id:selectedId,tags:$('#file-tags').value});toast('File tags saved.');await renderSearch();});
  listen('#copy-path','click',async()=>{await navigator.clipboard.writeText(file.path);toast('Local file path copied.');});
  listen('#similar-files','click',async()=>{const result=await get('similar',{id:selectedId});modal('Files with similar meaning',`<p class="muted small">${E(result.method)}</p>${result.results.length?result.results.map(r=>`<div class="check-row"><div><strong>${E(r.name)}</strong><p>Model similarity: ${E((r.semantic_score||0).toFixed(3))}</p><p>${E(r.path)}</p></div></div>`).join(''):empty('No similar text found','Index more documents of this type to compare them.','search')}`);});
}
async function renderFolders(){
  $('#view').innerHTML=pageHead('INDEX CONTROL','Choose what enters the index.','Nothing is scanned until you add a folder and start an index job.',button('load-demo','Load demo folder','folder','primary'))
  +`<div class="split"><div><div class="panel"><div class="panel-head"><h2>Add a folder</h2></div><div class="panel-body"><label class="field">Folder path<div class="input-row"><input id="folder-path" value="${E(info.example_path)}">${button('choose-folder','Browse','folder')}</div></label><label class="field">Extra exclusions<input id="exclude-patterns" placeholder="*.tmp, cache, private-notes"><small>.git, .env, .ssh, virtual environments, and app data are excluded by default.</small></label><label class="check-label"><input type="checkbox" id="enable-ocr" ${info.capabilities.ocr?'':'disabled'}>Use local Tesseract OCR for images and scanned PDFs ${info.capabilities.ocr?'':'(not installed)'}</label>${button('add-folder','Add and index folder','plus','primary')}</div></div><div class="panel"><div class="panel-head"><h2>Indexed folders</h2>${badge(state.roots.length+' folders')}</div>${state.roots.length?state.roots.map(r=>`<div class="panel-body" style="border-bottom:1px solid var(--line)"><div class="row-between"><h3>${E(r.name)}</h3>${badge(r.ocr?'OCR enabled':'Text files')}</div><p class="mono tiny muted" style="overflow-wrap:anywhere">${E(r.path)}</p><p class="tiny muted">Last scan: ${E(when(r.last_scan))}${r.last_error?' · '+E(r.last_error):''}</p><div class="section-actions"><button class="btn secondary" data-scan-root="${r.id}">${icon('refresh')} Rescan</button><button class="btn ghost" data-force-root="${r.id}">Verify all hashes</button><button class="btn ghost" data-remove-root="${r.id}">${icon('trash')} Forget index</button></div></div>`).join(''):empty('No folders added','Add a folder above or load the demo files.')}</div></div><div><div class="panel"><div class="panel-head"><h2>Automatic rescans</h2>${badge(state.watcher.enabled?'Running':'Off',state.watcher.enabled?'good':'')}</div><div class="panel-body"><p class="muted small">Enabled rescans resume after the vault unlocks. Stop rescans here to keep them disabled after restart.</p><label class="field">Seconds between scans<input id="watch-seconds" type="number" min="15" max="86400" value="${state.watcher.seconds}"></label><div class="section-actions">${button('start-watch','Start rescans','play','primary')}${button('stop-watch','Stop','pause')}</div>${state.watcher.last_error?`<p class="small" style="margin-top:12px">${E(state.watcher.last_error)}</p>`:''}</div></div><div class="notice info">${icon('shield')}<span>Forgetting an index removes its stored text and tags. It does not delete source files. Keep database backups private.</span></div></div></div>`;
  listen('#load-demo','click',demo);
  listen('#choose-folder','click',async()=>{const path=await pickPath($('#folder-path').value);if(path)$('#folder-path').value=path;});
  listen('#add-folder','click',async()=>{const root=await post('roots/add',{path:$('#folder-path').value,patterns:$('#exclude-patterns').value.split(',').map(s=>s.trim()).filter(Boolean),ocr:$('#enable-ocr').checked});await runJob('scan',{id:root.id});await refresh();await renderFolders();toast('Folder indexed.');});
  listen('[data-scan-root],[data-force-root]','click',async(_,node)=>{await runJob('scan',{id:Number(node.dataset.scanRoot||node.dataset.forceRoot),force:Boolean(node.dataset.forceRoot)});await refresh();await renderFolders();toast('Index scan complete.');});
  listen('[data-remove-root]','click',async(_,node)=>{await post('roots/remove',{id:Number(node.dataset.removeRoot)});await refresh();await renderFolders();toast('Stored index removed. Source files are unchanged.');});
  listen('#start-watch','click',async()=>{await post('watch/start',{seconds:Number($('#watch-seconds').value)});await refresh();await renderFolders();});
  listen('#stop-watch','click',async()=>{await post('watch/stop');await refresh();await renderFolders();});
}
async function route(tab){currentTab=tab;await refresh();
  if(tab==='search')return renderSearch();if(tab==='folders')return renderFolders();
  if(tab==='duplicates'){
    const result=await get('duplicates');
    $('#view').innerHTML=pageHead('BYTE-IDENTICAL COPIES','Find duplicate files safely.','Files with the same SHA-256 hash contain the same indexed bytes.')+stats([['Duplicate groups',result.groups.length,'Up to 100 groups are shown','copy'],['Extra duplicate bytes',bytes(result.extra_bytes),'Review copies before deleting anything','folder']])+`<div class="notice info">${icon('shield')}<span>${E(result.note)}</span></div>`+(result.groups.length?result.groups.map(g=>`<div class="panel"><div class="panel-head"><h2>${g.count} identical copies</h2>${badge(bytes(g.size)+' each','accent')}</div><div class="panel-body"><p class="hash-line">SHA-256 ${E(g.sha256)}</p></div>${g.files.map(f=>`<div class="file-row">${fileIcon(f.name)}<div class="file-main"><strong>${E(f.name)}</strong><small title="${E(f.path)}" class="overflow-path">${E(f.path)}</small></div></div>`).join('')}</div>`).join(''):`<div class="panel">${empty('No duplicate groups','Index the demo folder to see the two matching warranty files.','copy')}</div>`);return;
  }
  if(tab==='saved'){
    $('#view').innerHTML=pageHead('SAVED SEARCHES','Keep useful searches close.','Saved searches store the query and filters, not a frozen result list.')+`<div class="panel">${state.saved.length?`<table><thead><tr><th>Name</th><th>Query</th><th>Filters</th><th>Actions</th></tr></thead><tbody>${state.saved.map(s=>`<tr><td><strong>${E(s.name)}</strong></td><td>${E(s.query||'All files')}</td><td>${E([s.extension,s.tag].filter(Boolean).join(', ')||'None')}</td><td><div class="section-actions"><button class="text-btn" data-open-saved="${s.id}">Open ${icon('arrow')}</button><button class="text-btn" data-delete-saved="${s.id}">Delete</button></div></td></tr>`).join('')}</tbody></table>`:empty('No saved searches','Run a search, then select Save search.','bookmark')}</div>`;
    listen('[data-open-saved]','click',(_,node)=>{const s=state.saved.find(x=>x.id===Number(node.dataset.openSaved));query=s.query;extension=s.extension;tag=s.tag;rootFilter='';location.hash='search';});
    listen('[data-delete-saved]','click',async(_,node)=>{await post('saved/delete',{id:Number(node.dataset.deleteSaved)});await route('saved');});return;
  }
  $('#view').innerHTML=pageHead('INDEX JOBS','Check completed scans.','Coverage notes stay attached to each file. A successful job does not mean every file had readable text.')+`<div class="panel">${jobsHTML(state.jobs)}</div>`;bindJobs();
}
mount(info,[['search','Search files','search'],['folders','Indexed folders','folder'],['duplicates','Duplicates','copy'],['saved','Saved searches','bookmark'],['jobs','Index jobs','clock']],route,guide);
